jobs:
  - name: build
    steps:
      - name: Set up Java
        run: |
          apt-get install -y openjdk-8-jdk-headless
          export JAVA_HOME=$(readlink -f /usr/bin/javac | sed "s:/bin/javac::")
          export PATH=$PATH:$JAVA_HOME/bin
      - name: Install Spark
        run: |
          wget -q https://archive.apache.org/dist/spark/spark-2.4.8/spark-2.4.8-bin-hadoop2.7.tgz
          tar xf spark-2.4.8-bin-hadoop2.7.tgz
          export SPARK_HOME=$(pwd)/spark-2.4.8-bin-hadoop2.7